namespace FFmpeg.AutoGen
{
	public enum AVClassCategory
	{
		AV_CLASS_CATEGORY_NA = 0,
		AV_CLASS_CATEGORY_INPUT = 1,
		AV_CLASS_CATEGORY_OUTPUT = 2,
		AV_CLASS_CATEGORY_MUXER = 3,
		AV_CLASS_CATEGORY_DEMUXER = 4,
		AV_CLASS_CATEGORY_ENCODER = 5,
		AV_CLASS_CATEGORY_DECODER = 6,
		AV_CLASS_CATEGORY_FILTER = 7,
		AV_CLASS_CATEGORY_BITSTREAM_FILTER = 8,
		AV_CLASS_CATEGORY_SWSCALER = 9,
		AV_CLASS_CATEGORY_SWRESAMPLER = 10,
		AV_CLASS_CATEGORY_DEVICE_VIDEO_OUTPUT = 40,
		AV_CLASS_CATEGORY_DEVICE_VIDEO_INPUT = 41,
		AV_CLASS_CATEGORY_DEVICE_AUDIO_OUTPUT = 42,
		AV_CLASS_CATEGORY_DEVICE_AUDIO_INPUT = 43,
		AV_CLASS_CATEGORY_DEVICE_OUTPUT = 44,
		AV_CLASS_CATEGORY_DEVICE_INPUT = 45,
		AV_CLASS_CATEGORY_NB = 46
	}
}
