namespace FFmpeg.AutoGen
{
	public enum AVPacketSideDataType
	{
		AV_PKT_DATA_PALETTE = 0,
		AV_PKT_DATA_NEW_EXTRADATA = 1,
		AV_PKT_DATA_PARAM_CHANGE = 2,
		AV_PKT_DATA_H263_MB_INFO = 3,
		AV_PKT_DATA_REPLAYGAIN = 4,
		AV_PKT_DATA_DISPLAYMATRIX = 5,
		AV_PKT_DATA_STEREO3D = 6,
		AV_PKT_DATA_AUDIO_SERVICE_TYPE = 7,
		AV_PKT_DATA_QUALITY_STATS = 8,
		AV_PKT_DATA_FALLBACK_TRACK = 9,
		AV_PKT_DATA_CPB_PROPERTIES = 10,
		AV_PKT_DATA_SKIP_SAMPLES = 70,
		AV_PKT_DATA_JP_DUALMONO = 71,
		AV_PKT_DATA_STRINGS_METADATA = 72,
		AV_PKT_DATA_SUBTITLE_POSITION = 73,
		AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL = 74,
		AV_PKT_DATA_WEBVTT_IDENTIFIER = 75,
		AV_PKT_DATA_WEBVTT_SETTINGS = 76,
		AV_PKT_DATA_METADATA_UPDATE = 77
	}
}
