namespace FFmpeg.AutoGen
{
	public enum AVSideDataParamChangeFlags
	{
		AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_COUNT = 1,
		AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_LAYOUT = 2,
		AV_SIDE_DATA_PARAM_CHANGE_SAMPLE_RATE = 4,
		AV_SIDE_DATA_PARAM_CHANGE_DIMENSIONS = 8
	}
}
