namespace FFmpeg.AutoGen
{
	public enum AVStreamParseType
	{
		AVSTREAM_PARSE_NONE = 0,
		AVSTREAM_PARSE_FULL = 1,
		AVSTREAM_PARSE_HEADERS = 2,
		AVSTREAM_PARSE_TIMESTAMPS = 3,
		AVSTREAM_PARSE_FULL_ONCE = 4,
		AVSTREAM_PARSE_FULL_RAW = 1463898624
	}
}
