namespace FFmpeg.AutoGen
{
	public enum SwrDitherType
	{
		SWR_DITHER_NONE = 0,
		SWR_DITHER_RECTANGULAR = 1,
		SWR_DITHER_TRIANGULAR = 2,
		SWR_DITHER_TRIANGULAR_HIGHPASS = 3,
		SWR_DITHER_NS = 0x40,
		SWR_DITHER_NS_LIPSHITZ = 65,
		SWR_DITHER_NS_F_WEIGHTED = 66,
		SWR_DITHER_NS_MODIFIED_E_WEIGHTED = 67,
		SWR_DITHER_NS_IMPROVED_E_WEIGHTED = 68,
		SWR_DITHER_NS_SHIBATA = 69,
		SWR_DITHER_NS_LOW_SHIBATA = 70,
		SWR_DITHER_NS_HIGH_SHIBATA = 71,
		SWR_DITHER_NB = 72
	}
}
