namespace FistVR
{
	public enum FirearmAudioEventType
	{
		Shots_Main = 100,
		Shots_Suppressed = 101,
		Shots_LowPressure = 102,
		BoltSlideForward = 0,
		BoltSlideBack = 1,
		BoltSlideForwardHeld = 2,
		BoltSlideBackHeld = 3,
		BoltSlideBackLocked = 4,
		CatchOnSear = 5,
		HammerHit = 6,
		Prefire = 7,
		BoltRelease = 8,
		HandleGrab = 9,
		HandleBack = 10,
		HandleForward = 11,
		HandleUp = 12,
		HandleDown = 13,
		Safety = 14,
		FireSelector = 0xF,
		TriggerReset = 0x10,
		BreachOpen = 17,
		BreachClose = 18,
		HandleForwardEmpty = 40,
		HandleBackEmpty = 41,
		ChamberManual = 42,
		MagazineIn = 20,
		MagazineOut = 21,
		TopCoverRelease = 22,
		TopCoverUp = 23,
		TopCoverDown = 24,
		MagazineInsertRound = 28,
		MagazineEjectRound = 29,
		StockOpen = 30,
		StockClosed = 0x1F,
		BipodOpen = 0x20,
		BipodClosed = 33,
		BeltGrab = 50,
		BeltRelease = 51,
		BeltSeat = 52,
		BeltSettle = 53
	}
}
