namespace FistVR
{
	public enum FVRFireArmMechanicalAccuracyClass
	{
		None = 0,
		PistolPrecision = 1,
		PistolHighEnd = 2,
		PistolAverage = 3,
		PistolPoor = 4,
		PistolTerrible = 5,
		PistolCapBall = 6,
		ShotgunPrecision = 10,
		ShotgunAverage = 11,
		ShotgunPoor = 12,
		SMGPrecision = 20,
		SMGClosedModern = 21,
		SMGOpenModern = 22,
		SMGMilsurp = 23,
		AutoRifleTopEnd = 30,
		AutoRiflePrecision = 0x1F,
		AutoRifleMatch = 0x20,
		AutoRifleModern = 33,
		AutoRifleMilsurp = 34,
		AutoRifleAntique = 35,
		BoltActionTopEnd = 40,
		BoltActionPrecision = 41,
		BoltActionModern = 42,
		BoltActionHunting = 43,
		BoltActionMilsurp = 44,
		BoltActionAntique = 45,
		LauncherGrenade = 50,
		LauncherSmoothbore = 51,
		MusketPrecision = 60,
		MusketAverage = 61,
		MusketPoor = 62,
		MusketPistol = 0x3F,
		SuppressorPrecision = 100,
		SuppressorAverage = 101,
		SuppressorMini = 102,
		SuppressorOld = 103,
		SuppressorShit = 104,
		SuppressorImprovised = 105,
		MuzzleBrakeWeak = 110,
		MuzzleBrakeAvg = 111,
		MuzzleBrakeStrong = 112,
		CompensatorModern = 118,
		CompensatorOld = 119,
		BarrelExtensionShort = 120,
		BarrelExtensionMed = 121,
		BarrelExtensionLong = 122,
		ShroudModern = 130,
		ShroudOlder = 131
	}
}
