namespace FistVR
{
	public enum TNH_VoiceLineID
	{
		AI_UplinkSuccessfulTargetSystemDetectedTakeIt = 0,
		AI_InterfacingWithSystemNode = 1,
		AI_AnalyzingSystem = 2,
		AI_EncryptionType_0 = 10,
		AI_EncryptionType_1 = 11,
		AI_EncryptionType_2 = 12,
		AI_EncryptionType_3 = 13,
		AI_EncryptionType_4 = 14,
		AI_EncryptionType_5 = 0xF,
		AI_EncryptionType_6 = 0x10,
		AI_EncryptionType_7 = 17,
		AI_EncryptionType_8 = 18,
		AI_EncryptionType_9 = 19,
		AI_EncryptionType_10 = 20,
		AI_EncryptionType_Unknown = 40,
		AI_Encryption_Neutralized = 50,
		AI_Encryption_Reminder1 = 60,
		AI_Encryption_Reminder2 = 61,
		AI_AdvancingToNextSystemLayer = 62,
		AI_HoldSuccessfulDataExtracted = 70,
		AI_HoldFailedNodeConnectionTerminated = 71,
		AI_AdvanceToNextSystemNodeAndTakeIt = 90,
		AI_OverrideTokenFound_1 = 91,
		AI_OverrideTokenFound_2 = 92,
		AI_OverrideTokenFound_3 = 93,
		AI_OverrideTokenFound_4 = 94,
		AI_OverrideTokenFound_5 = 95,
		AI_ResourceStorageFound = 100,
		AI_ToolConstructorFound = 101,
		AI_RegenerationModuleFound = 102,
		AI_SystemCoreExposedDestroyIt = 110,
		AI_SystemCoreDestroyedWellDone = 111,
		AI_PlayerConnectionFailure = 120,
		AI_ReturningToInterface = 121,
		AI_TerminalOperatorFailureSystemConnectionLost = 122,
		BASE_IntrusionDetectedInitiatingLockdown = 500,
		BASE_ResponseTeamEnRoute = 501,
		BASE_DispatchingAdditionalResponseTeam = 502,
		BASE_EncryptionCompromised = 503,
		BASE_FabricatingDefenseSystems = 504,
		BASE_ErrorSystemFailure = 505
	}
}
